apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-playground
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/hnaciri/conf
    targetRevision: 0.0.0
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
